theme: jekyll-theme-cayman
title: Soviet Writers' Social Network
author: Stephen Zq
description: This scheme represents interactions and ties between the Soviet children’s writers between 1953-1956. It would make evident how the considerable liberation in this field took place, and how personal efforts and interpersonal ties influenced it. 
